### ISSUE TITLE
Unplayable

### ISSUE THREAD

**Issue by LIttleAncientForestKami** [AdrianHarenczyk/OX#16]
See log in issue comment

**Comment by LIttleAncientForestKami** [comment]
Please provide player name.
0
Now please choose symbol.
0
This symbol is not supported.

Please provide player name.
0
Now please choose symbol.
1
This symbol is not supported.

Please provide player name.
0
Now please choose symbol.
x
Please provide player name.
a
0 with symbol X
?
a with symbol O
?
0 with symbol X
?
a with symbol O
1
0 with symbol X
2
a with symbol O
3
0 with symbol X
4
a with symbol O
5
0 with symbol X
6
a with symbol O
7
0 with symbol X
8
a with symbol O
5
0 with symbol X
6
a with symbol O
87
0 with symbol X
6
a with symbol O
2
0 with symbol X
3
a with symbol O
4
0 with symbol X
5
a with symbol O
y
0 with symbol X
n
a with symbol O
sa
0 with symbol X

**Comment by AdrianHarenczyk** [comment]
Patch is in the way. It is corrected in that version. Will be live after merge.
