### ISSUE TITLE
Game end needs additional actions

### ISSUE THREAD

**Issue by boczkas** [AdrianHarenczyk/OX#25]
Requirement:
After the game ends, process should end too.

It looks like additional step is needed to end aplication.

It would be better to end when results are shown.
```
 with symbol X points: 4
 with symbol O points: 4

 with symbol O wins the round!
The game has ended. Press enter to see the results.

It's a draw!

To exit application, press enter.

**Comment by AdrianHarenczyk** [comment]
For me it's good like this :) I will leave it as it is.
